MbmStore/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MbmStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace MbmStore.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult Index()
        {

            // create a new Movie object with instance name jungleBook
            var jungleBook = new Movie(34,"Jungle Book", 160.50m, "junglebook.jpg","");
            var wizardBook = new Movie(35,"The Wizard of Oz", 230.75m, "twoo.jpg","");
            var aliceBook = new Movie(67,"Alice in Wonderland", 130.50m, "junglebook.jpg","");

            List<object> books = new List<object>();
            books.Add(jungleBook);
            books.Add(wizardBook);
            books.Add(aliceBook);

            // assign a ViewBag property to the new Movie object
            ViewBag.Books = books;

            // return the default view
            return View();
        }
    }
}

MbmStore/Areas/Admin/Views/Shared/_layout.cshtml
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">MbmStore Admnistration</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" asp-controller="Music" asp-action="Index">Music</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Book" asp-action="Index">Books</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Movie" asp-action="Index">Movies</a>
            </li>
        </ul>
    </div>
</nav>

<div>
    @RenderBody()
</div>