MbmStore/Components/CartSummaryViewComponent.cs
using MbmStore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
namespace MbmStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

MbmStore/Controllers/CartController.cs
using MbmStore.Infrastructure;
using MbmStore.Models;
using MbmStore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using MbmStore.Data;

namespace MbmStore.Controllers
{
    public class CartController : Controller
    {
        private Cart cart;

        private MbmStoreContext dataContext;
        public CartController(MbmStoreContext dbContext, Cart cartService)
        {
            dataContext = dbContext;
            cart = cartService;
        }

        //public CartController(Cart cartService)
        //{
        //    cart = cartService;
        //}
        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public RedirectToActionResult AddToCart(int productId, string returnUrl, int qty)
        {
            Product product = dataContext.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                cart.AddItem(product, qty);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
        {
            Product product = dataContext.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

MbmStore/Controllers/CatalogueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using MbmStore.Models;
using MbmStore.Models.ViewModels;
using MbmStore.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using MbmStore.Data;

namespace MbmStore.Controllers
{
    public class CatalogueController : Controller
    {
        private MbmStoreContext dataContext;
        private int PageSize { get; } = 4;

        public CatalogueController(MbmStoreContext dbContext) { 
            dataContext = dbContext; 
        }

        public IActionResult Index(string category, int page = 1)
        {



            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = dataContext.Products
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductId)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? dataContext.Products.Count() : dataContext.Products.Where(e => e.Category == category).Count()
                },

                CurrentCategory = category
            };
            return View(model);
        }
    }
}

MbmStore/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using MbmStore.Models;
using MbmStore.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MbmStore.Data;
using Microsoft.EntityFrameworkCore;

namespace MbmStore.Controllers
{
    public class InvoiceController : Controller
    {

        private MbmStoreContext dataContext;

        public InvoiceController(MbmStoreContext dbContext)
        {
            dataContext = dbContext;
          
        }
     
        
        public IActionResult Index()
        {

            List<SelectListItem> customers = new List<SelectListItem>();


            // generate the dropdown list
            foreach (Invoice invoice in dataContext.Invoices.Include(invoice => invoice.Customer))
            {

                customers.Add(new SelectListItem
                {
                    Text = invoice.Customer.Firstname + " " + invoice.Customer.Lastname,
                    Value = invoice.Customer.CustomerId.ToString()
                });

               
            }

            // removes duplicate entries with same ID from a IEnumerable
            customers = customers.GroupBy(x => x.Value).Select(y => y.First()).OrderBy(z => z.Text).ToList<SelectListItem>();

            ViewBag.Invoices = dataContext.Invoices.Include(invoice => invoice.OrderItems).ThenInclude(orderItem => orderItem.Product);
            ViewBag.Customers = customers;
            return View();
        }

        [HttpPost]
        public IActionResult Index(int? customer)
        {


           

            List<Invoice> invoices = new List<Invoice>();


            if (customer != null)
            {
                // select invoices for a customer with linq
                invoices = dataContext.Invoices.Include(invoice => invoice.Customer).Include(invoice => invoice.OrderItems).ThenInclude(orderItem => orderItem.Product).Where(r => r.Customer.CustomerId == customer).ToList();
            }
            else
            {
                invoices = dataContext.Invoices.Include(invoice => invoice.OrderItems).ThenInclude(orderItem => orderItem.Product).ToList();
            }

            // declare the list
            List<SelectListItem> customers = new List<SelectListItem>();

            // generate the dropdown list, med selected vist
            foreach (Invoice invoice in dataContext.Invoices.Include(invoice => invoice.Customer))
            {
                if (invoice.Customer.CustomerId == customer)
                {
                    customers.Add(new SelectListItem
                    {
                        Text = invoice.Customer.Firstname + " " + invoice.Customer.Lastname,
                        Value = invoice.Customer.CustomerId.ToString(),
                        Selected = (invoice.Customer.CustomerId == customer)
                    });
                }
                else
                {

                    customers.Add(new SelectListItem
                    {
                        Text = invoice.Customer.Firstname + " " + invoice.Customer.Lastname,
                        Value = invoice.Customer.CustomerId.ToString()
                    });
                }

            }

            // removes duplicate entries with same ID from a IEnumerable
            customers = customers.GroupBy(x => x.Value).Select(y => y.First()).OrderBy(z => z.Text).ToList<SelectListItem>();

            ViewBag.Invoices = invoices;
            ViewBag.Customers = customers;

            return View();
        }
    }
}

MbmStore/Views/Shared/_AddToCartButton.cshtml
@model MbmStore.Models.Product
@using MbmStore.Infrastructure


<div>

    <form id="@Model.ProductId" asp-action="AddToCart" asp-controller="Cart" method="post">
        <input type="hidden" name="ProductId" value="@Model.ProductId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="addtocard">
            <span>Quantity:</span>
            <select name="qty" id="qty">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
            </select>
            <button type="submit">
                Add To Cart
            </button>
        </span>
    </form>
</div>

MbmStore/Views/Shared/_Layout.cshtml
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" asp-href-include="/lib/font-awesome/css/*.css" />
    <link rel="stylesheet" asp-href-include="/css/styles.css" />
</head>
<body>

    <div id="wrapper">
        <div id="topbar"><h1><a asp-action="Index" asp-controller="Catalogue" asp-route-category="">The very awesome MBM shop</a></h1> <span>Jesper Kragh | Backend progammering | oct 2020</span></div>
        <div id="menu">
            <div class="cart-summary"> @await Component.InvokeAsync("CartSummary") </div>
        </div>


        <div id="content">
            <div class="leftcol">
                @await Component.InvokeAsync("NavigationMenu")
            </div>
            <div>
                @RenderBody()
            </div>
        </div>


    </div>
    <a class="invoicelink" asp-controller="Invoice" asp-action="Index">Invoices</a>

</body>
</html>

MbmStore/Views/Shared/_ProductSummaryBook.cshtml
@model MbmStore.Models.Book
@using MbmStore.Models;


<div class="product">

    <img src="/Images/@Model.ImageFileName" alt="@Model.Title" />
    <h3>@Model.Title</h3>
    <h4>By: @Model.Author</h4>
    <p><b>Publisher:</b> @Model.Publisher</p>
    <p>Price: @String.Format("{0:0.00}", Model.Price)</p>
    <div class="clear"></div>

    @await Html.PartialAsync("_AddToCartButton", (Product)Model)
</div>

MbmStore/Views/Shared/_ProductSummaryMovie.cshtml
@model MbmStore.Models.Movie
@using MbmStore.Models;

<div class="product">

    <img src="/Images/@Model.ImageFileName" alt="@Model.Title" />
    <h3>@Model.Title</h3>
    <h4>By: @Model.Director</h4>
    <p>Price: @String.Format("{0:0.00}", Model.Price)</p>
    <div class="clear"></div>


    @await Html.PartialAsync("_AddToCartButton", (Product)Model)
</div>

MbmStore/Views/Shared/_ProductSummaryMusicCD.cshtml
@model MbmStore.Models.MusicCD
@using MbmStore.Models;


<div class="product">


    <div>
        <img src="/Images/@Model.ImageFileName" alt="@Model.Title" />

        <h3>@Model.Title</h3>
        <h4>By: @Model.Artist</h4>
        <p><b>Released:</b> @Model.Released</p>
        <p><b>Label:</b> @Model.Label</p>
        <p><b>Price:</b> @String.Format("{0:0.00}", Model.Price)</p>

    </div>
    <div class="clear"></div>
    <b>Tracks:</b>
    <ol>

        @foreach (Track track in @Model.Tracks)
        {
            <li>
                @track.Title (@track.Composer)
                @track.Length.ToString()
            </li>

        }
    </ol>
    <p><b>Total playtime: @Model.TotalPlayingTime()</b></p>


    @await Html.PartialAsync("_AddToCartButton", (Product)Model)
</div>